apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: harbor.tecklab.dk/teck-lab/catalog-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__postgres-write
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secrets
                  key: postgres-write
            - name: ConnectionStrings__postgres-read
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secrets
                  key: postgres-read
            - name: ConnectionStrings__rabbitmq
              valueFrom:
                secretKeyRef:
                  name: shared-platform-secrets
                  key: rabbitmq
            - name: ConnectionStrings__redis
              valueFrom:
                secretKeyRef:
                  name: shared-platform-secrets
                  key: redis
            - name: Services__CustomerApi__Url
              value: "http://customer-api.teck-cloud.svc.cluster.local"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
