apiVersion: v1
kind: Service
metadata:
  name: web-bff
  labels:
    app: web-bff
spec:
  selector:
    app: web-bff
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
